### ISSUE TITLE
Well Known types doesn't work

### ISSUE THREAD

**Issue by misha-plus** [go-bridget/twirp-swagger-gen#1]
Hello. The project looks nice. Trying to use it against my Proto file. But have error regarding to the standard timestamp.
```
syntax = "proto3";

package com.example;
option go_package = "./rpc";

import "google/protobuf/timestamp.proto";

message TheType {
    oneof min_time_opt {
        google.protobuf.Timestamp min_time    = 3;
        Empty                     no_min_time = 4;
    }
}
```

```
panic: open google/protobuf/timestamp.proto: no such file or directory

goroutine 1 [running]:
main.(*SwaggerWriter).Import(0xc0001760c0, 0xc000012070)
	/Users/michael/gopath/src/github.com/go-bridget/twirp-swagger-gen/main.go:71 +0x354
github.com/emicklei/proto.WithImport.func1(0x13e55e0, 0xc000012070)
	/Users/michael/gopath/src/github.com/emicklei/proto/walk.go:49 +0x42
github.com/emicklei/proto.walk(0x13e7de0, 0xc00038a9c0, 0xc0002a65c0, 0x4, 0x4)
	/Users/michael/gopath/src/github.com/emicklei/proto/walk.go:37 +0x74
github.com/emicklei/proto.Walk(...)
	/Users/michael/gopath/src/github.com/emicklei/proto/walk.go:31
main.parse(0x7ffeefbff70d, 0x10, 0x7ffeefbff6de, 0xd, 0x7ffeefbff6f1, 0x15, 0xd, 0x0)
	/Users/michael/gopath/src/github.com/go-bridget/twirp-swagger-gen/main.go:344 +0x150
main.main()
	/Users/michael/gopath/src/github.com/go-bridget/twirp-swagger-gen/main.go:370 +0x27d
```

**Comment by melias122** [comment]
@misha-plus, you can try to use it with https://buf.build. That works for me.

**Comment by melias122** [comment]
No I was wrong (I had protoc twrip plugin in ~/bin). @titpetric can you explain how to use this with e.g. buf.build to workaround this issue.

**Comment by titpetric** [comment]
Can you symlink the google folder for the workaround?

**Comment by delaneyj** [comment]
That doesn't work as well.  Even copying the proto doesn't work.

**Comment by titpetric** [comment]
Can you produce a .proto example for me to test?

**Comment by titpetric** [comment]
Ok, two things:

1. I've changed the generator to ignore missing files (instead of ending up in a panic),
2. *spec.Oneof is not implemented anyway, it should be reasonably trivial to submit a PR if you need it

**Comment by matthiasbruns** [comment]
`2021/11/22 13:55:33  info Can't load google/protobuf/empty.proto, err=open google/protobuf/empty.proto: The system cannot find the path specified., ignoring
2021/11/22 13:55:33  info Can't load google/protobuf/timestamp.proto, err=open google/protobuf/timestamp.proto: The system cannot find the path specified., ignoring
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xa00180]
`

Having the same error - any updates on this?

**Comment by titpetric** [comment]
I'm only using native types, so I don't know what to do about this
particular issue. If you can explain in detail what needs to end up in the
swagger json for the timestamp type, then I could probablly glue the .proto
files together, that produce the output. The first thing should be the
availability of the .proto files for inclusion, which should be trivial
(error message specified which file can't be opened), and then either it
works, or it falls into one of those yet unhandled cases.

**Comment by titpetric** [comment]
Ok, I've implemented and tested two things:

- added option `-I <path>`, specify an additional include path (likely -I /usr/src/include for your case)
- added support for *proto.Oneof (see examples/)
- tested with timestamp.proto (also present under examples/)

I can't be sure if the output for swagger in regards to *Oneof is correct. Looks good to me, but there are some custom semantics regarding Oneof, which possibly get lost in translation to swagger.

**Comment by titpetric** [comment]
> No I was wrong (I had protoc twrip plugin in ~/bin). @titpetric can you explain how to use this with e.g. buf.build to workaround this issue.

@melias122 I'm not using buf build, but I suspect you'd use it as an extra step outside buf. If buf uses existing protoc plugins, then unfortunately, this project isn't built as a protoc plugin and you won't be able to use it from buf.

**Comment by melias122** [comment]
I have a wip implementation for this repo to work as protoc plugin, then it can be added to e.g. buf. I will make a PR when its ready and as I have more time on it.

Martin Elias

**Comment by titpetric** [comment]
Currently twirp-swagger-gen uses an external proto parser, so I could avoid
a dependency on google repositories. Backwards compatibility there isn't
much of a thing, which is also why the original swagger-gen is broken
today. As long as the proto parser code remains the same, the protoc/buf
support is welcome.

**Comment by melias122** [comment]
To make this work with protoc plugin system, we would need at least  theese imports
```
"google.golang.org/protobuf/proto"
"google.golang.org/protobuf/types/descriptorpb"
"google.golang.org/protobuf/types/pluginpb"
```

My plan to implement plugin support:
- move SwaggerWriter to separate package
- move your implementation under cmd/
- implement cmd/protoc-gen-twirp-swagger protoc plugin to work with SwaggerWriter

Suggestions are welcome too.

**Comment by melias122** [comment]
Or maybe just not do the `cmd` and only add `protoc-gen-twirp-swagger` subdir similair to what twrip is doing with protoc plugin.

**Comment by titpetric** [comment]
I'm fine with the first suggestion, two folders under cmd. You can move
swaggerwriter under internal/ so there's not a public api surface

**Comment by melias122** [comment]
Added PR with plugin support. I think we should create a separate issue to document what types are not supported yet. Like map, and also known types such as Duration or Wrappers. Also we should try to match `https://github.com/elliots/protoc-gen-twirp_swagger` output as much as possible.

**Comment by titpetric** [comment]
Sounds good to me.

**Comment by titpetric** [comment]
@melias122 you don't need to jump on this, but a good idea would be to add a protoc readme.md section that updates the go get/go run/go install usage, and adds protoc / buf usage examples. I'll likely do it during the next few weeks, unless you're willing to field another PR improving this before then?

**Comment by melias122** [comment]
@titpetric sorry, I am now a bit busy before xmas. Maybe later, if so I will make an issue.

**Comment by titpetric** [comment]
Well known types reference from a different generator: https://github.com/partitio/micro-gateway/blob/master/protoc-gen-swagger/genswagger/template.go

**Comment by titpetric** [comment]
Sure, no problem. Enjoy your holidays, I'll reserve some time over the next
few days.

**Comment by titpetric** [comment]
Added the well known types from the genswagger list.
