### ISSUE TITLE
Go install `module found but does not contain package`

### ISSUE THREAD

**Issue by antonioorct** [go-bridget/twirp-swagger-gen#4]
Running the following command to install the package:
```
go install github.com/go-bridget/twirp-swagger-gen@latest
```
Produces the following error:
```
go install github.com/go-bridget/twirp-swagger-gen@latest:
module github.com/go-bridget/twirp-swagger-gen@latest found (v0.0.0-20211215193339-cc7af6432fca), but does not contain package github.com/go-bridget/twirp-swagger-gen
```

Running `go get` does not do anything and also does not work

If possible please consider providing releases and tags so we can use a fixed version of this package

**Comment by titpetric** [comment]
The README.md is out of date, can you try adding `/cmd/...` to the go install url, or the particular folder under cmd/ for either the stand-alone version, or for the protoc version also usable by buf, this should solve it for you.

Releases and tags will be considered in the future, when the use case stabilizes a bit. Currently, you could pin a particular commit hash which works for you. I could possibly tag a 0.1 and 0.2 versions, but at this point, the main value is keeping up with `@latest`.

**Comment by titpetric** [comment]
Updated readme.
