### ISSUE TITLE
OpenAPI 3.0 Support

### ISSUE THREAD

**Issue by casimcdaniels** [go-bridget/twirp-swagger-gen#8]
Is there any interest in supporting OpenAPI 3.0?

**Comment by titpetric** [comment]
I currently don't have a use case beyond 2.0/swagger, wasn't too happy about openapi 3.0 libraries for some reason (I do forget why), and would not accept a PR adding this functionality. If you're willing and able, I'd suggest you fork and add openapi 3.0 outputs, and then support that fork indefinitely on your own. I could look at implementing it myself and then support it going forward, if you're in a position to sponsor that. Let me know :)
